In [1]:
import pandas as pd

In [2]:
london_poi_df = pd.read_csv("API Data/London_poi.csv", index_col=[0])
london_attractions_df = pd.read_csv("API Data/London_attractions.csv", index_col=[0])

In [3]:
london_poi_df

,ID,Name,Address,Category,Location,Lat,Lng,Details,Subcategory,Polarity
0,79137,Platform 2 Heathrow T1&3,NaN,poi,London,51.494021,-0.433203,http://tour-pedia.org/api/getPlaceDetails?id=7...,Platform,0
1,79144,Black Cab 40799,NaN,poi,London,51.398279,-0.300245,http://tour-pedia.org/api/getPlaceDetails?id=7...,Taxi,0
2,79148,Hampstead Pound,NaN,poi,London,51.567634,-0.179068,http://tour-pedia.org/api/getPlaceDetails?id=7...,General Travel,0
3,79149,Orchard Street Car Park,NaN,poi,London,51.488441,-0.308320,http://tour-pedia.org/api/getPlaceDetails?id=7...,Parking,0
4,79153,"Erith, Bus Stop G",NaN,poi,London,51.480666,0.178808,http://tour-pedia.org/api/getPlaceDetails?id=7...,Bus Station,0
...,...,...,...,...,...,...,...,...,...,...
80505,49635,Simply dental,80-112 The Green,poi,London,51.444490,-0.344294,http://tour-pedia.org/api/getPlaceDetails?id=4...,Dentist's Office,0
80506,49650,Moor Lane,Moor Lane,poi,London,51.565792,0.273893,http://tour-pedia.org/api/getPlaceDetails?id=4...,Road,0
80507,49665,Kidbrooke Park Road,NaN,poi,London,51.472118,0.023026,http://tour-pedia.org/api/getPlaceDetails?id=4...,Road,0
80508,49689,Long Lane,Anywhere!,poi,London,51.467959,0.144116,http://tour-pedia.org/api/getPlaceDetails?id=4...,Road,0
80509,49715,"Trinity road, east finchley",NaN,poi,London,51.598692,-0.149345,http://tour-pedia.org/api/getPlaceDetails?id=4...,Road,0

In [ ]:
subcat = london_poi_df['Subcategory'].value_counts()
subcat

In [ ]:
to_small = list(subcat[subcat <= 5].index)
to_small

In [ ]:
maybe = list(subcat[subcat > 5].index)
maybe

In [ ]:
maybe_df = (subcat[subcat > 5])
maybe_df

In [ ]:
london_attractions_df

In [ ]:
subcat_att = london_attractions_df['Category'].value_counts()
subcat_att

In [ ]:
total_poi_cat = list(subcat[subcat >= 1].index)
total_poi_cat

In [11]:
not_wanted = ["Dentist's Office", 'Airport Gate', 'Airport Terminal', 'Home (private)',
             'Office', 'Coworking Space', 'Military Base', 'Residential Building (Apartment / Condo)', 'Eye Doctor', 
              'Voting Booth', 'Conference Room', 'Veterinarian', 'Fire Station', 'Police Station', 'Post Office', 
              'Professional & Other Places', 'College Science Building', 'Hotel', 'College Academic Building', 
             'School', 'General College & University']
airport = ['Airport Lounge', 'Airport Tram', 'Airport Food Court']
medical = ['Medical Center', "Doctor's Office", 'Hospital', 'Emergency Room', ]
misc = ['Grocery Store', 'Cosmetics Shop', 'Gaming Cafe', 'Coffee Shop', 'Mall', 'Plaza']
water = ['Pier', 'Harbor / Marina']
history = ['History Museum', 'Historic Site', 'Museum']
lib = ['College Library']

In [12]:
london_poi_df.drop(london_poi_df.loc[london_poi_df.Subcategory.isin(not_wanted)].index, inplace=True)
london_poi_df.loc[london_poi_df.Subcategory.isin(airport)] = 'Airport'
london_poi_df.loc[london_poi_df.Subcategory.isin(medical)] = 'Medical Building'
london_poi_df.loc[london_poi_df.Subcategory.isin(misc)] = 'Miscellaneous Shop'
london_poi_df.loc[london_poi_df.Subcategory.isin(water)] = 'Pier / Marina'
london_poi_df.loc[london_poi_df.Subcategory.isin(history)] = 'Museum / Historic Site'
london_poi_df.loc[london_poi_df.Subcategory.isin(lib)] = 'Library'

In [13]:
#london_cleaned.head()
london_poi_df

,ID,Name,Address,Category,Location,Lat,Lng,Details,Subcategory,Polarity
0,79137,Platform 2 Heathrow T1&3,NaN,poi,London,51.494021,-0.433203,http://tour-pedia.org/api/getPlaceDetails?id=7...,Platform,0
1,79144,Black Cab 40799,NaN,poi,London,51.398279,-0.300245,http://tour-pedia.org/api/getPlaceDetails?id=7...,Taxi,0
2,79148,Hampstead Pound,NaN,poi,London,51.567634,-0.179068,http://tour-pedia.org/api/getPlaceDetails?id=7...,General Travel,0
3,79149,Orchard Street Car Park,NaN,poi,London,51.488441,-0.30832,http://tour-pedia.org/api/getPlaceDetails?id=7...,Parking,0
4,79153,"Erith, Bus Stop G",NaN,poi,London,51.480666,0.178808,http://tour-pedia.org/api/getPlaceDetails?id=7...,Bus Station,0
...,...,...,...,...,...,...,...,...,...,...
80504,49632,Tower Hamlets One Stop Shop,NaN,poi,London,51.514777,-0.058699,http://tour-pedia.org/api/getPlaceDetails?id=4...,Government Building,0
80506,49650,Moor Lane,Moor Lane,poi,London,51.565792,0.273893,http://tour-pedia.org/api/getPlaceDetails?id=4...,Road,0
80507,49665,Kidbrooke Park Road,NaN,poi,London,51.472118,0.023026,http://tour-pedia.org/api/getPlaceDetails?id=4...,Road,0
80508,49689,Long Lane,Anywhere!,poi,London,51.467959,0.144116,http://tour-pedia.org/api/getPlaceDetails?id=4...,Road,0
80509,49715,"Trinity road, east finchley",NaN,poi,London,51.598692,-0.149345,http://tour-pedia.org/api/getPlaceDetails?id=4...,Road,0

In [14]:
sbcats = london_poi_df['Subcategory'].value_counts()
sbcats

-                             69467
Road                           2387
Bus Line                       1295
Medical Building               1237
Bus Station                     986
Train Station                   483
Platform                        416
Government Building             397
Moving Target                   386
General Travel                  299
Parking                         259
Subway                          247
Train                           207
Taxi                            195
Rental Car Location             176
Plane                           173
Convention Center               167
Library                         136
Meeting Room                    112
Monument / Landmark             109
Light Rail                      106
Boat or Ferry                    92
Airport                          83
Rest Area                        65
City Hall                        56
Courthouse                       45
Embassy / Consulate              43
Bike Rental / Bike Share         36
Capitol Building                 31
Pier / Marina                    31
Tourist Information Center       17
Laboratory                       17
Travel Lounge                    13
Event Space                      10
Building                         10
Miscellaneous Shop                8
Museum / Historic Site            7
Art Gallery                       3
General Entertainment             2
Pub                               1
Name: Subcategory, dtype: int64

In [15]:
test = london_poi_df[london_poi_df['Subcategory'].str.contains("-")]
test

,ID,Name,Address,Category,Location,Lat,Lng,Details,Subcategory,Polarity
196,80076,Deantist,NaN,poi,London,51.519481,0.196233,http://tour-pedia.org/api/getPlaceDetails?id=8...,-,-
264,80427,Fulham RdChelsea & W'minster (Stop HK),United Kingdom,poi,London,51.484455,-0.184639,http://tour-pedia.org/api/getPlaceDetails?id=8...,-,-
1075,50329,Walworth Police Station,"London, United Kingdom",poi,London,51.489316,-0.097535,http://tour-pedia.org/api/getPlaceDetails?id=5...,-,-
1542,53074,Marsh House,98 London Road,poi,London,51.417162,-0.162124,http://tour-pedia.org/api/getPlaceDetails?id=5...,-,-
1553,53139,Romford Station L (Stop W),United Kingdom,poi,London,51.574635,0.184973,http://tour-pedia.org/api/getPlaceDetails?id=5...,-,-
...,...,...,...,...,...,...,...,...,...,...
80266,47653,Kneller Hall (Stop A),United Kingdom,poi,London,51.453812,-0.347995,http://tour-pedia.org/api/getPlaceDetails?id=4...,-,-
80308,47989,Ilford Police Station,"Ilford, United Kingdom",poi,London,51.560173,0.080048,http://tour-pedia.org/api/getPlaceDetails?id=4...,-,-
80321,48094,Greenwich Police Station,"London, United Kingdom",poi,London,51.477992,-0.00992,http://tour-pedia.org/api/getPlaceDetails?id=4...,-,-
80383,48611,Dalston Job Centre,NaN,poi,London,51.545138,-0.076683,http://tour-pedia.org/api/getPlaceDetails?id=4...,-,-
80446,49205,Harlesden Police Station (Stop F),United Kingdom,poi,London,51.541088,-0.254375,http://tour-pedia.org/api/getPlaceDetails?id=4...,-,-

In [16]:
london_poi_df.loc[london_poi_df.Name.isin(test.Name)] = 'Point of Interest'
london_poi_df['Subcategory'].value_counts()

Point of Interest             69636
Road                           2330
Bus Line                       1293
Medical Building               1237
Bus Station                     978
Train Station                   482
Platform                        416
Government Building             388
Moving Target                   385
General Travel                  291
Subway                          247
Parking                         246
Train                           206
Taxi                            192
Rental Car Location             176
Plane                           173
Convention Center               165
Meeting Room                    111
Monument / Landmark             106
Light Rail                      104
Library                          95
Boat or Ferry                    90
Airport                          82
Rest Area                        65
City Hall                        52
Embassy / Consulate              41
Courthouse                       39
Bike Rental / Bike Share         36
Capitol Building                 31
Pier / Marina                    31
Tourist Information Center       17
Laboratory                       17
Travel Lounge                    13
Building                         10
Event Space                       8
Miscellaneous Shop                8
Museum / Historic Site            7
Art Gallery                       3
General Entertainment             2
Pub                               1
Name: Subcategory, dtype: int64

In [17]:
#london_poi_df = london_poi_df[london_poi_df['lat'].notnull()]
london_poi_df.count()

ID             79810
Name           79810
Address        75155
Category       79810
Location       79810
Lat            79810
Lng            79810
Details        79810
Subcategory    79810
Polarity       79810
dtype: int64

In [18]:
#london_attractions_df = london_attractions_df[london_attractions_df['lat'].notnull()]
london_attractions_df.count()

ID          20727
Name        20727
Address     14163
Category    20727
Location    20727
Lat         20727
Lng         20727
Details     20727
dtype: int64

In [19]:
to_pubs = london_attractions_df[london_attractions_df['Name'].str.contains(" pub")]
to_pubs.drop(to_pubs.loc[to_pubs.Name.isin(['The Albert public house', 'The windmill public house'])].index, inplace=True)
to_pubs

C:\Users\Laura\anaconda3\envs\mlenv\lib\site-packages\pandas\core\frame.py:4315: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,ID,Name,Address,Category,Location,Lat,Lng,Details
5182,79987,cherry tree pub,NaN,attraction,London,51.643580,-0.138361,http://tour-pedia.org/api/getPlaceDetails?id=7...
5720,81951,Guffaw comedy club upstairs at ye olde rose & ...,55 Hoe Street,attraction,London,51.589112,-0.021405,http://tour-pedia.org/api/getPlaceDetails?id=8...
5919,82648,Hyde arms pub,137 Victoira rd,attraction,London,51.622636,-0.065757,http://tour-pedia.org/api/getPlaceDetails?id=8...
6218,50469,Halfway pub,Mayfield road,attraction,London,51.483846,0.164205,http://tour-pedia.org/api/getPlaceDetails?id=5...
6573,52801,Royal Oak pub Harrow,NaN,attraction,London,51.606676,-0.300886,http://tour-pedia.org/api/getPlaceDetails?id=5...
7233,56294,Harvest home pub,NaN,attraction,London,51.369106,-0.126332,http://tour-pedia.org/api/getPlaceDetails?id=5...
7547,57744,The Woolpack pub,NaN,attraction,London,51.579385,-0.040510,http://tour-pedia.org/api/getPlaceDetails?id=5...
9013,64652,Watermark pub,NaN,attraction,London,51.463572,-0.068706,http://tour-pedia.org/api/getPlaceDetails?id=6...
9123,65222,Old bell pub kilburn high rd,Kilburn high rd,attraction,London,51.546674,-0.208698,http://tour-pedia.org/api/getPlaceDetails?id=6...
9201,65575,Old bell pub garden,Kilburn high rd,attraction,London,51.539886,-0.252857,http://tour-pedia.org/api/getPlaceDetails?id=6...
10303,70521,the turrets pub,Friern Barnet Road,attraction,London,51.642549,-0.160628,http://tour-pedia.org/api/getPlaceDetails?id=7...
11375,75144,war bank pub,NaN,attraction,London,51.339395,0.010152,http://tour-pedia.org/api/getPlaceDetails?id=7...
12276,78833,Fox And Hounds pub,NaN,attraction,London,51.548280,0.021351,http://tour-pedia.org/api/getPlaceDetails?id=7...
12564,42322,Lord Nelson pub,NaN,attraction,London,51.379864,-0.218589,http://tour-pedia.org/api/getPlaceDetails?id=4...
12826,216743,Asparagus pub battersea,"1-13 Falcon Rd, London SW11 2PL , London, , Un...",attraction,London,51.469985,-0.171744,http://tour-pedia.org/api/getPlaceDetails?id=2...
14734,39150,Hand & Flower pub,"617 Kings Road, Chelsea",attraction,London,51.477867,-0.189640,http://tour-pedia.org/api/getPlaceDetails?id=3...
14959,40377,The castle pub,Barking road,attraction,London,51.525593,0.029599,http://tour-pedia.org/api/getPlaceDetails?id=4...
15216,41795,Edge of Town pub,Station Road,attraction,London,51.615385,-0.275601,http://tour-pedia.org/api/getPlaceDetails?id=4...
15436,43067,Miller and Carter pub and steakhouse,NaN,attraction,London,51.584293,-0.431942,http://tour-pedia.org/api/getPlaceDetails?id=4...
15760,44961,Princess Alice pub,Gallions Reach,attraction,London,51.498506,0.089525,http://tour-pedia.org/api/getPlaceDetails?id=4...
16092,47239,The Cardinal pub,174 Tudor Drive,attraction,London,51.426502,-0.298114,http://tour-pedia.org/api/getPlaceDetails?id=4...
16403,49463,Malt Shovel pub,NaN,attraction,London,51.529516,-0.485606,http://tour-pedia.org/api/getPlaceDetails?id=4...
19592,38405,The Star pub,158 Plumstead common road,attraction,London,51.487718,0.124456,http://tour-pedia.org/api/getPlaceDetails?id=3...
19785,41925,The Minstrel Boy pub,colney hatch lane,attraction,London,51.609403,-0.151333,http://tour-pedia.org/api/getPlaceDetails?id=4...
19988,44216,Plough pub,NaN,attraction,London,51.367680,-0.132228,http://tour-pedia.org/api/getPlaceDetails?id=4...
20023,44585,Change Of Hart pub,High Street,attraction,London,51.609302,-0.277877,http://tour-pedia.org/api/getPlaceDetails?id=4...
20170,45866,Hollywood East pub,NaN,attraction,London,51.419475,-0.055811,http://tour-pedia.org/api/getPlaceDetails?id=4...
20484,48248,Ye old pub,NaN,attraction,London,51.391828,-0.039724,http://tour-pedia.org/api/getPlaceDetails?id=4...

In [20]:
london_attractions_df.loc[london_attractions_df.Name.isin(to_pubs.Name)] = 'Pub'
london_attractions_df['Category'].value_counts()

attraction    20699
Pub              28
Name: Category, dtype: int64

In [21]:
to_gallery = london_attractions_df[london_attractions_df['Name'].str.contains("gallery")]
to_gallery

,ID,Name,Address,Category,Location,Lat,Lng,Details
32,245479,theLOCALgallery,"14 Avenue Mews, London, United Kingdom",attraction,London,51.590715,-0.144017,http://tour-pedia.org/api/getPlaceDetails?id=2...
1874,246215,De Parma @ domus gallery,"15 Needham Road, London, United Kingdom",attraction,London,51.515367,-0.197449,http://tour-pedia.org/api/getPlaceDetails?id=2...
1941,246297,W3 gallery,"185 High Street, London, United Kingdom",attraction,London,51.506742,-0.268887,http://tour-pedia.org/api/getPlaceDetails?id=2...
1976,246347,CALKEN gallery,"117 Kensington Church Street, London, United K...",attraction,London,51.506557,-0.194688,http://tour-pedia.org/api/getPlaceDetails?id=2...
2411,246933,gallery @ 44 Emerald Street,"44 Emerald St, London, United Kingdom",attraction,London,51.522198,-0.105798,http://tour-pedia.org/api/getPlaceDetails?id=2...
2480,247037,gallery235,"Bayswater Road, London, United Kingdom",attraction,London,51.511255,-0.177846,http://tour-pedia.org/api/getPlaceDetails?id=2...
2565,247143,Zero10 gallery,"6 Silver Place, London, United Kingdom",attraction,London,51.513092,-0.135927,http://tour-pedia.org/api/getPlaceDetails?id=2...
3029,247761,Unit 24 gallery,"20 Great Guildford St, London, United Kingdom",attraction,London,51.505872,-0.097545,http://tour-pedia.org/api/getPlaceDetails?id=2...
3475,248338,galleryf,"459 Roman Road, London, United Kingdom",attraction,London,51.532068,-0.034667,http://tour-pedia.org/api/getPlaceDetails?id=2...
3509,248381,ICN gallery & cafe,"96 Leonard Street, London, United Kingdom",attraction,London,51.524612,-0.081592,http://tour-pedia.org/api/getPlaceDetails?id=2...
3522,248401,Nog gallery,"182 Brick Lane, London, United Kingdom",attraction,London,51.523532,-0.071354,http://tour-pedia.org/api/getPlaceDetails?id=2...
3698,248642,a & c gallery,"115 Trafalgar Rd, London, United Kingdom",attraction,London,51.484313,0.001864,http://tour-pedia.org/api/getPlaceDetails?id=2...
3964,248966,gallery63A,"63a Park Road, Kingston upon Thames, United Ki...",attraction,London,51.415942,-0.288489,http://tour-pedia.org/api/getPlaceDetails?id=2...
4269,249353,bettie morton gallery,"62 Atlantic Road, London, United Kingdom",attraction,London,51.461166,-0.111395,http://tour-pedia.org/api/getPlaceDetails?id=2...
4271,249356,GXgallery,"43 Denmark Hill, London, United Kingdom",attraction,London,51.471695,-0.092892,http://tour-pedia.org/api/getPlaceDetails?id=2...
4462,249579,tate158artgallery,"131 Langdale Road, Thornton Heath, United Kingdom",attraction,London,51.399984,-0.109784,http://tour-pedia.org/api/getPlaceDetails?id=2...
4507,249632,[mine] creative space and art gallery,"30-34 High Street Carshalton Sutton, Surrey SM...",attraction,London,51.365192,-0.161356,http://tour-pedia.org/api/getPlaceDetails?id=2...
4592,249737,New Crossgallery,"3 Lewisham Way, New Cross, London, SE14 6PP, U...",attraction,London,51.469379,-0.02822,http://tour-pedia.org/api/getPlaceDetails?id=2...
4609,249761,Greenwich printmakers gallery,"1a Greenwich Market, London, United Kingdom",attraction,London,51.481365,-0.009165,http://tour-pedia.org/api/getPlaceDetails?id=2...
4610,249763,The flood gallery,"8 Greenwich Market, London, United Kingdom",attraction,London,51.481346,-0.00863,http://tour-pedia.org/api/getPlaceDetails?id=2...
5296,80354,One love gallery,NaN,attraction,London,51.596815,-0.126987,http://tour-pedia.org/api/getPlaceDetails?id=8...
6085,83252,Arebyte gallery,"Unit 4, 49 White Post Lane",attraction,London,51.542942,-0.023287,http://tour-pedia.org/api/getPlaceDetails?id=8...
18966,247726,gallery@oxo,"Oxo Tower Wharf, Barge House Street, South Ban...",attraction,London,51.50826,-0.108217,http://tour-pedia.org/api/getPlaceDetails?id=2...
19388,249702,BEARSPACE gallery,"152 Deptford High Street, London, United Kingdom",attraction,London,51.479226,-0.025975,http://tour-pedia.org/api/getPlaceDetails?id=2...
19810,42229,"stables gallery, nw26ht",gladstone park,attraction,London,51.560016,-0.236849,http://tour-pedia.org/api/getPlaceDetails?id=4...

In [22]:
london_attractions_df.loc[london_attractions_df.Name.isin(to_gallery.Name)] = 'Gallery'
london_attractions_df['Category'].value_counts()

attraction    20674
Pub              28
Gallery          25
Name: Category, dtype: int64

In [23]:
london_poi_df.head()#["Details"]

,ID,Name,Address,Category,Location,Lat,Lng,Details,Subcategory,Polarity
0,79137,Platform 2 Heathrow T1&3,NaN,poi,London,51.494021,-0.433203,http://tour-pedia.org/api/getPlaceDetails?id=7...,Platform,0
1,79144,Black Cab 40799,NaN,poi,London,51.398279,-0.300245,http://tour-pedia.org/api/getPlaceDetails?id=7...,Taxi,0
2,79148,Hampstead Pound,NaN,poi,London,51.567634,-0.179068,http://tour-pedia.org/api/getPlaceDetails?id=7...,General Travel,0
3,79149,Orchard Street Car Park,NaN,poi,London,51.488441,-0.30832,http://tour-pedia.org/api/getPlaceDetails?id=7...,Parking,0
4,79153,"Erith, Bus Stop G",NaN,poi,London,51.480666,0.178808,http://tour-pedia.org/api/getPlaceDetails?id=7...,Bus Station,0

In [24]:
london_attractions_df#.head()["Details"]

,ID,Name,Address,Category,Location,Lat,Lng,Details
0,216987,Hennessy Pub,"London, , United Kingdom",attraction,London,51.572641,-0.412705,http://tour-pedia.org/api/getPlaceDetails?id=2...
1,217081,The O2 Arena,"London, , United Kingdom",attraction,London,51.520852,-0.016405,http://tour-pedia.org/api/getPlaceDetails?id=2...
2,245715,The Gym Ealing,"96-122 Uxbridge Road, London, United Kingdom",attraction,London,51.511485,-0.316286,http://tour-pedia.org/api/getPlaceDetails?id=2...
3,245714,Virgin Active - Ealing,"5th Floor, Ealing Broadway Centre, London, Uni...",attraction,London,51.512153,-0.302852,http://tour-pedia.org/api/getPlaceDetails?id=2...
4,245710,PM Gallery & House,"Walpole Park, Mattock Lane, London, United Kin...",attraction,London,51.511019,-0.307122,http://tour-pedia.org/api/getPlaceDetails?id=2...
...,...,...,...,...,...,...,...,...
20722,49693,Playground Behind Ruislip High Street,Hillingdon,attraction,London,51.575709,-0.424862,http://tour-pedia.org/api/getPlaceDetails?id=4...
20723,49695,Langdon Playground,Langdon Park,attraction,London,51.42113,-0.313565,http://tour-pedia.org/api/getPlaceDetails?id=4...
20724,49697,The Beehive,Stoneleigh Rd,attraction,London,51.592264,-0.069498,http://tour-pedia.org/api/getPlaceDetails?id=4...
20725,49701,Zippos Circus At Twickenham,13-29 The Green,attraction,London,51.444234,-0.341313,http://tour-pedia.org/api/getPlaceDetails?id=4...
20726,49705,Jews For Jesus,Kentish Town Road,attraction,London,51.545551,-0.141387,http://tour-pedia.org/api/getPlaceDetails?id=4...

In [25]:
poi_df = pd.DataFrame(columns=["Name", "Geometry", "Address", "Lattitude", "Longitude", "Category"])
poi_df["Name"] = london_poi_df["Name"]
poi_df["Geometry"] = "POINT(" + london_poi_df["Lat"].astype(str) + " " + london_poi_df["Lng"].astype(str) + ")"
poi_df["Address"] = london_poi_df["Address"]
poi_df["Category"] = london_poi_df["Subcategory"]
poi_df["Lattitude"] = london_poi_df["Lat"]
poi_df["Longitude"] = london_poi_df["Lng"]
poi_df

,Name,Geometry,Address,Lattitude,Longitude,Category
0,Platform 2 Heathrow T1&3,POINT(51.494021270321 -0.43320281182828),NaN,51.494021,-0.433203,Platform
1,Black Cab 40799,POINT(51.398279 -0.300245),NaN,51.398279,-0.300245,Taxi
2,Hampstead Pound,POINT(51.567634 -0.179068),NaN,51.567634,-0.179068,General Travel
3,Orchard Street Car Park,POINT(51.488441 -0.30832),NaN,51.488441,-0.30832,Parking
4,"Erith, Bus Stop G",POINT(51.480666 0.178808),NaN,51.480666,0.178808,Bus Station
...,...,...,...,...,...,...
80504,Tower Hamlets One Stop Shop,POINT(51.514777 -0.058699),NaN,51.514777,-0.058699,Government Building
80506,Moor Lane,POINT(51.5657918 0.27389275),Moor Lane,51.565792,0.273893,Road
80507,Kidbrooke Park Road,POINT(51.472118352142 0.02302582238949),NaN,51.472118,0.023026,Road
80508,Long Lane,POINT(51.467959191425 0.14411572305863),Anywhere!,51.467959,0.144116,Road
80509,"Trinity road, east finchley",POINT(51.598691744062 -0.14934490079138),NaN,51.598692,-0.149345,Road

In [26]:
attract_df = pd.DataFrame(columns=["Name", "Geometry", "Address", "Lattitude", "Longitude", "Category"])
attract_df["Name"] = london_attractions_df["Name"]
attract_df["Geometry"] = "POINT(" + london_attractions_df["Lat"].astype(str) + " " + london_attractions_df["Lng"].astype(str) + ")"
attract_df["Address"] = london_attractions_df["Address"]
attract_df["Category"] = london_attractions_df["Category"]
attract_df["Lattitude"] = london_attractions_df["Lat"]
attract_df["Longitude"] = london_attractions_df["Lng"]
attract_df

,Name,Geometry,Address,Lattitude,Longitude,Category
0,Hennessy Pub,POINT(51.572640909349 -0.41270504408679),"London, , United Kingdom",51.572641,-0.412705,attraction
1,The O2 Arena,POINT(51.5208524812 -0.016405034172),"London, , United Kingdom",51.520852,-0.016405,attraction
2,The Gym Ealing,POINT(51.511485 -0.316286),"96-122 Uxbridge Road, London, United Kingdom",51.511485,-0.316286,attraction
3,Virgin Active - Ealing,POINT(51.512153 -0.302852),"5th Floor, Ealing Broadway Centre, London, Uni...",51.512153,-0.302852,attraction
4,PM Gallery & House,POINT(51.511019 -0.307122),"Walpole Park, Mattock Lane, London, United Kin...",51.511019,-0.307122,attraction
...,...,...,...,...,...,...
20722,Playground Behind Ruislip High Street,POINT(51.575708985329 -0.42486190795898),Hillingdon,51.575709,-0.424862,attraction
20723,Langdon Playground,POINT(51.42112976 -0.31356539),Langdon Park,51.42113,-0.313565,attraction
20724,The Beehive,POINT(51.592264 -0.069498),Stoneleigh Rd,51.592264,-0.069498,attraction
20725,Zippos Circus At Twickenham,POINT(51.444234 -0.34131291),13-29 The Green,51.444234,-0.341313,attraction
20726,Jews For Jesus,POINT(51.545551 -0.141387),Kentish Town Road,51.545551,-0.141387,attraction

In [27]:
london_df = pd.DataFrame(columns=["Name", "Geometry", "Address", "Lattitude", "Longitude", "Category"])
london_df = london_df.append(attract_df, ignore_index=True)
london_df = london_df.append(poi_df, ignore_index=True)
london_df

,Name,Geometry,Address,Lattitude,Longitude,Category
0,Hennessy Pub,POINT(51.572640909349 -0.41270504408679),"London, , United Kingdom",51.572641,-0.412705,attraction
1,The O2 Arena,POINT(51.5208524812 -0.016405034172),"London, , United Kingdom",51.520852,-0.016405,attraction
2,The Gym Ealing,POINT(51.511485 -0.316286),"96-122 Uxbridge Road, London, United Kingdom",51.511485,-0.316286,attraction
3,Virgin Active - Ealing,POINT(51.512153 -0.302852),"5th Floor, Ealing Broadway Centre, London, Uni...",51.512153,-0.302852,attraction
4,PM Gallery & House,POINT(51.511019 -0.307122),"Walpole Park, Mattock Lane, London, United Kin...",51.511019,-0.307122,attraction
...,...,...,...,...,...,...
100532,Tower Hamlets One Stop Shop,POINT(51.514777 -0.058699),NaN,51.514777,-0.058699,Government Building
100533,Moor Lane,POINT(51.5657918 0.27389275),Moor Lane,51.565792,0.273893,Road
100534,Kidbrooke Park Road,POINT(51.472118352142 0.02302582238949),NaN,51.472118,0.023026,Road
100535,Long Lane,POINT(51.467959191425 0.14411572305863),Anywhere!,51.467959,0.144116,Road
100536,"Trinity road, east finchley",POINT(51.598691744062 -0.14934490079138),NaN,51.598692,-0.149345,Road

In [28]:
london_df.count()

Name         100537
Geometry     100537
Address       89332
Lattitude    100537
Longitude    100537
Category     100537
dtype: int64

In [29]:
len(pd.unique(london_df['Geometry']))

29349

In [30]:
len(pd.unique(london_df['Name']))

26216

In [31]:
london_unique = london_df.drop_duplicates(subset=['Name'], ignore_index=True)

In [32]:
len(pd.unique(london_unique['Geometry']))

26067

In [33]:
london_unique.count()

Name         26216
Geometry     26216
Address      15915
Lattitude    26216
Longitude    26216
Category     26216
dtype: int64

In [34]:
london_unique['Category'].value_counts()

attraction                    18791
Road                           2146
Bus Line                       1085
Bus Station                     765
Moving Target                   368
Government Building             343
Train Station                   321
General Travel                  272
Subway                          219
Train                           196
Taxi                            189
Plane                           172
Convention Center               162
Parking                         157
Platform                        122
Meeting Room                    108
Monument / Landmark              96
Light Rail                       92
Library                          89
Rental Car Location              83
Boat or Ferry                    81
Rest Area                        63
City Hall                        50
Embassy / Consulate              41
Courthouse                       39
Airport                          36
Capitol Building                 29
Bike Rental / Bike Share         27
Laboratory                       16
Tourist Information Center       16
Travel Lounge                    12
Building                         10
Event Space                       7
Art Gallery                       3
General Entertainment             2
Miscellaneous Shop                2
Pub                               1
Pier / Marina                     1
Museum / Historic Site            1
Medical Building                  1
Gallery                           1
Point of Interest                 1
Name: Category, dtype: int64

In [35]:
london_unique.to_csv("Resources/LondonTotal.csv")