LONDON RESTAURANTS, TYPE, LOCATION, RATINGS, and LOCATION

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import json

# Import API key
from config import api_key

Yelp Business Search API Documentation: https://www.yelp.com/developers/documentation/v3/business_search

In [2]:
# headers contain the api key.
# reference this site for set up: https://www.justintodata.com/python-api-call-to-request-data/
headers = {"Authorization": "Bearer {}".format(api_key)}
search_api_url = "https://api.yelp.com/v3/businesses/search"

Yelp Business Search API default returns twenty records at a time. However, the API allows fifty records per call by adding a limit to the parameters, with four calls maximum before returning an error. So, the maximum dataset size is 200 records.

In [3]:
#First set of 50 records 0-50
lndr_params1 = {"term":"Austrian","location":"London","limit":50,"offset":0}
lndr_response1 = requests.get(search_api_url, headers=headers, params=lndr_params1)
lndr1 = lndr_response1.json()
display(lndr1)
#print(lndr_response1.url)
#print(lndr_response1.status_code)

{'businesses': [{'id': '-_6mjiQuPMMR7VvLb3v92A',
   'alias': 'cafe-vienna-london',
   'name': 'Cafe Vienna',
   'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/RviJORqhUuTql8UsIaCXyA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/cafe-vienna-london?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 3,
   'categories': [{'alias': 'austrian', 'title': 'Austrian'}],
   'rating': 5.0,
   'coordinates': {'latitude': 51.4968262, 'longitude': -0.1684469},
   'transactions': [],
   'price': '££',
   'location': {'address1': '235 Brompton road',
    'address2': None,
    'address3': '',
    'city': 'London',
    'zip_code': 'SW3 2EP',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['235 Brompton road',
     'London SW3 2EP',
     'United Kingdom']},
   'phone': '+442075840953',
   'display_phone': '+44 20 7584 0953',
   'distance': 2872.010011559581},
  {'id': 'apqNvjbaB20wozywrLNPiQ',
   'alias': 'fischers-london',
   'name': "Fischer's",
   'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/A68yx91bh-81NvBKkMXVCg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/fischers-london?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 37,
   'categories': [{'alias': 'austrian', 'title': 'Austrian'},
    {'alias': 'german', 'title': 'German'}],
   'rating': 4.0,
   'coordinates': {'latitude': 51.5216155579831,
    'longitude': -0.151699820819173},
   'transactions': [],
   'price': '£££',
   'location': {'address1': '50 Marylebone High Street',
    'address2': '',
    'address3': '',
    'city': 'London',
    'zip_code': 'W1U 5HN',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['50 Marylebone High Street',
     'London W1U 5HN',
     'United Kingdom']},
   'phone': '+442074665501',
   'display_phone': '+44 20 7466 5501',
   'distance': 1462.850471845834},
  {'id': 'xqpUr61KFa1Xx721-E6l_A',
   'alias': 'kipferl-london-6',
   'name': 'Kipferl',
   'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/CUoYGTlW1CYS-nJ5vAUGPw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/kipferl-london-6?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 47,
   'categories': [{'alias': 'coffee', 'title': 'Coffee & Tea'},
    {'alias': 'modern_european', 'title': 'Modern European'},
    {'alias': 'austrian', 'title': 'Austrian'}],
   'rating': 4.0,
   'coordinates': {'latitude': 51.535247538411,
    'longitude': -0.10339315152949},
   'transactions': [],
   'price': '££',
   'location': {'address1': '20 Camden Passage',
    'address2': '',
    'address3': '',
    'city': 'London',
    'zip_code': 'N1 8ED',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['20 Camden Passage',
     'London N1 8ED',
     'United Kingdom']},
   'phone': '+442077041555',
   'display_phone': '+44 20 7704 1555',
   'distance': 3359.4222431551457},
  {'id': 'QTRkMjYHXAVROidXkkt7Ow',
   'alias': 'the-delaunay-london-3',
   'name': 'The Delaunay',
   'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/zz7VMc8u_hhSOuIphETZLA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/the-delaunay-london-3?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 118,
   'categories': [{'alias': 'modern_european', 'title': 'Modern European'},
    {'alias': 'breakfast_brunch', 'title': 'Breakfast & Brunch'}],
   'rating': 4.0,
   'coordinates': {'latitude': 51.5131115, 'longitude': -0.1182553},
   'transactions': [],
   'price': '£££',
   'location': {'address1': '55 Aldwych',
    'address2': None,
    'address3': '',
    'city': 'London',
    'zip_code': 'WC2B 4BB',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['55 Aldwych', 'London WC2B 4BB', 'United Kingdom']},
   'phone': '+442074998558',
   'display_phone': '+44 20 7499 8558',
   'distance': 1233.9810795843225},
  {'id': 'sen5D3KKE0penBC7d5GlUQ',
   'alias': 'zeitgeist-london-3',
   'name': 'Zeitgeist',
   'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/zuld2QQENVx6CJmJ36AWSw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/zeitgeist-london-3?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 28,
   'categories': [{'alias': 'german', 'title': 'German'}],
   'rating': 4.0,
   'coordinates': {'latitude': 51.491333, 'longitude': -0.1182021},
   'transactions': [],
   'price': '££',
   'location': {'address1': '49 - 51 Black Prince Road',
    'address2': 'Lambeth',
    'address3': '',
    'city': 'London',
    'zip_code': 'SE11 6AB',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['49 - 51 Black Prince Road',
     'Lambeth',
     'London SE11 6AB',
     'United Kingdom']},
   'phone': '+442078400426',
   'display_phone': '+44 20 7840 0426',
   'distance': 2684.618353612666},
  {'id': 'Ou2WL4kvXL0Z93b3h0mAdQ',
   'alias': 'the-delaunay-counter-london-2',
   'name': 'The Delaunay Counter',
   'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/LYhCrQ-zRqzx01YQF3GVLg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/the-delaunay-counter-london-2?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 1,
   'categories': [{'alias': 'cafes', 'title': 'Cafes'},
    {'alias': 'austrian', 'title': 'Austrian'}],
   'rating': 4.0,
   'coordinates': {'latitude': 51.5131115, 'longitude': -0.1182553},
   'transactions': [],
   'location': {'address1': '55 Aldwych',
    'address2': '',
    'address3': None,
    'city': 'London',
    'zip_code': 'WC2B 4BB',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['55 Aldwych', 'London WC2B 4BB', 'United Kingdom']},
   'phone': '+442078713990',
   'display_phone': '+44 20 7871 3990',
   'distance': 1233.9810795843225},
  {'id': '4IpNjfnu3VnM8p7_i4or4Q',
   'alias': 'german-gymnasium-london-2',
   'name': 'German Gymnasium',
   'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/TmJEnHXlhw3juq9561WDQA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/german-gymnasium-london-2?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 52,
   'categories': [{'alias': 'german', 'title': 'German'}],
   'rating': 4.0,
   'coordinates': {'latitude': 51.5323975443626,
    'longitude': -0.125419827905187},
   'transactions': [],
   'price': '£££',
   'location': {'address1': '1 Kings Boulevard',
    'address2': '',
    'address3': '',
    'city': 'London',
    'zip_code': 'N1C 4AG',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['1 Kings Boulevard',
     'London N1C 4AG',
     'United Kingdom']},
   'phone': '+442072878000',
   'display_phone': '+44 20 7287 8000',
   'distance': 2294.086392187214},
  {'id': 'jcBeMcH_nAaDDJotomqs-g',
   'alias': 'katzenjammers-london',
   'name': 'Katzenjammers',
   'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/Wam1D3XSLBf1uOjRuXOh_g/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/katzenjammers-london?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 48,
   'categories': [{'alias': 'german', 'title': 'German'},
    {'alias': 'pubs', 'title': 'Pubs'}],
   'rating': 3.5,
   'coordinates': {'latitude': 51.504827352652,
    'longitude': -0.0910319201774978},
   'transactions': [],
   'price': '££',
   'location': {'address1': '24 Southwark Street',
    'address2': '',
    'address3': '',
    'city': 'London',
    'zip_code': 'SE1 1TY',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['24 Southwark Street',
     'London SE1 1TY',
     'United Kingdom']},
   'phone': '+447771363542',
   'display_phone': '+44 7771 363542',
   'distance': 3234.0535001935},
  {'id': 'PEgAoJeVtVAbmuNKUWa-wg',
   'alias': '10-greek-street-london',
   'name': '10 Greek Street',
   'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/-88bKhhTr5nVtN6hxERGlA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/10-greek-street-london?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 51,
   'categories': [{'alias': 'modern_european', 'title': 'Modern European'}],
   'rating': 4.5,
   'coordinates': {'latitude': 51.5144981659116,
    'longitude': -0.131063461303711},
   'transactions': [],
   'price': '£££',
   'location': {'address1': '10 Greek Street',
    'address2': '',
    'address3': '',
    'city': 'London',
    'zip_code': 'W1D 4DH',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['10 Greek Street',
     'London W1D 4DH',
     'United Kingdom']},
   'phone': '+442077344677',
   'display_phone': '+44 20 7734 4677',
   'distance': 385.73947726767943},
  {'id': 'GXGXX8Eapy5yBpLTx-N1kw',
   'alias': 'munich-cricket-club-london-3',
   'name': 'Munich Cricket Club',
   'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/_3TswQ46hIQxri5qJvMl0w/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/munich-cricket-club-london-3?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 9,
   'categories': [{'alias': 'german', 'title': 'German'}],
   'rating': 3.5,
   'coordinates': {'latitude': 51.4980721, 'longitude': -0.1325256},
   'transactions': [],
   'price': '££',
   'location': {'address1': '1 Abbey Orchard Street',
    'address2': '',
    'address3': '',
    'city': 'London',
    'zip_code': 'SW1P 2LU',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['1 Abbey Orchard Street',
     'London SW1P 2LU',
     'United Kingdom']},
   'phone': '+442072228972',
   'display_phone': '+44 20 7222 8972',
   'distance': 1658.6942639754977},
  {'id': 'DJH9kKABJZHkJ4Xz8b168w',
   'alias': 'oblix-at-the-shard-london',
   'name': 'Oblix At The Shard',
   'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/Bs25-Wqvmbn8IDIxKV7zWw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/oblix-at-the-shard-london?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 114,
   'categories': [{'alias': 'lounges', 'title': 'Lounges'},
    {'alias': 'modern_european', 'title': 'Modern European'}],
   'rating': 4.0,
   'coordinates': {'latitude': 51.5052532, 'longitude': -0.0869875},
   'transactions': [],
   'price': '££££',
   'location': {'address1': 'Level 32 The Shard',
    'address2': '31 St Thomas Street',
    'address3': '',
    'city': 'London',
    'zip_code': 'SE1 9SY',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['Level 32 The Shard',
     '31 St Thomas Street',
     'London SE1 9SY',
     'United Kingdom']},
   'phone': '+442072686700',
   'display_phone': '+44 20 7268 6700',
   'distance': 3492.235471085661},
  {'id': 'HmZmhDt7fFG39K7hGo3mqA',
   'alias': 'kalendar-cafe-london',
   'name': 'Kalendar Cafe',
   'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/DHXl0nqw7CUIL-NmjVmbIw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/kalendar-cafe-london?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 29,
   'categories': [{'alias': 'coffee', 'title': 'Coffee & Tea'},
    {'alias': 'modern_european', 'title': 'Modern European'},
    {'alias': 'breakfast_brunch', 'title': 'Breakfast & Brunch'}],
   'rating': 3.5,
   'coordinates': {'latitude': 51.5620028, 'longitude': -0.1498279},
   'transactions': [],
   'price': '££',
   'location': {'address1': '15a Swains Lane',
    'address2': '',
    'address3': '',
    'city': 'London',
    'zip_code': 'N6 6QX',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['15a Swains Lane', 'London N6 6QX', 'United Kingdom']},
   'phone': '+442083488300',
   'display_phone': '+44 20 8348 8300',
   'distance': 5551.145166436271},
  {'id': 'wb6FeERexO4mECAd2eM54Q',
   'alias': 'the-paperworks-london',
   'name': 'The Paperworks',
   'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/gOclfcHxvukGuTqPkUFu5w/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/the-paperworks-london?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 3,
   'categories': [{'alias': 'streetvendors', 'title': 'Street Vendors'},
    {'alias': 'austrian', 'title': 'Austrian'}],
   'rating': 4.5,
   'coordinates': {'latitude': 51.498024, 'longitude': -0.0984994},
   'transactions': [],
   'location': {'address1': '48 - 50 Newington Causeway',
    'address2': '',
    'address3': '',
    'city': 'London',
    'zip_code': 'SE1 6DR',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['48 - 50 Newington Causeway',
     'London SE1 6DR',
     'United Kingdom']},
   'phone': '+442074036164',
   'display_phone': '+44 20 7403 6164',
   'distance': 3068.151865011475},
  {'id': 'ov2m0xEjirn1Gll0MOhUqw',
   'alias': 'marcus-london-2',
   'name': 'Marcus',
   'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/TwsxSfpVNIKtS1c6NnNTHg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/marcus-london-2?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 59,
   'categories': [{'alias': 'french', 'title': 'French'},
    {'alias': 'modern_european', 'title': 'Modern European'},
    {'alias': 'british', 'title': 'British'}],
   'rating': 4.0,
   'coordinates': {'latitude': 51.5016612, 'longitude': -0.1556969},
   'transactions': [],
   'price': '££££',
   'location': {'address1': 'The Berkeley',
    'address2': 'Wilton Place',
    'address3': '',
    'city': 'London',
    'zip_code': 'SW1X 7RL',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['The Berkeley',
     'Wilton Place',
     'London SW1X 7RL',
     'United Kingdom']},
   'phone': '+442072351200',
   'display_phone': '+44 20 7235 1200',
   'distance': 1846.7706605199148},
  {'id': 'eXNSn0FwCeSmDHDlDWzv5w',
   'alias': 'steins-london',
   'name': "Stein's",
   'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/BVMPsMmPHU5B8ypSGTGH3A/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/steins-london?adjust_creative=-uBzzloii2ivvF3N0jkhKQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=-uBzzloii2ivvF3N0jkhKQ',
   'review_count': 25,
   'categories': [{'alias': 'pubs', 'title': 'Pubs'},
    {'alias': 'gastropubs', 'title': 'Gastropubs'},
    {'alias': 'german', 'title': 'German'}],
   'rating': 3.5,
   'coordinates': {'latitude': 51.455546, 'longitude': -0.304016},
   'transactions': [],
   'price': '££',
   'location': {'address1': 'Richmond Towpath',
    'address2': '55 Petersham Road',
    'address3': '',
    'city': 'London',
    'zip_code': 'TW10 6UX',
    'country': 'GB',
    'state': 'XGL',
    'display_address': ['Richmond Towpath',
     '55 Petersham Road',
     'London TW10 6UX',
     'United Kingdom']},
   'phone': '+442089488189',
   'display_phone': '+44 20 8948 8189',
   'distance': 13266.710868756603}],
 'total': 15,
 'region': {'center': {'longitude': -0.135955810546875,
   'latitude': 51.51283552118349}}}

In [4]:
#Create a for loop to capture the data of the first 50 records 0-50

#Create Empty Lists
lat1=[]
lng1=[]
address1=[]
name1=[]
title1=[]
price1=[]
rating1=[]
ids1=[]
url1=[]

#Set Counter to 0
i = 0

#For Loop with Try/Except Error
for i in (lndr1["businesses"]):
    try:
        lat1.append (i["coordinates"]["latitude"])
        lng1.append (i["coordinates"]["longitude"])
        address1.append (i["location"]["address1"])
        name1.append (i["name"])    
        title1.append(i["categories"][0]["title"])
        price1.append (i["price"])
        rating1.append (i["rating"])
        ids1.append (i["id"])
        url1.append (i["url"])
    except(KeyError,IndexError):
        print("Skipping, Not Found")
        price1.append("")
        rating1.append("")
        ids1.append("")
        url1.append("")

Skipping, Not Found
Skipping, Not Found

In [5]:
#Create DataFrame of the first 50 records collected 
df1 = pd.DataFrame({"Restaurant": name1,"Type": title1, "Price":price1, "Rating":rating1, "Address":address1, "Lat":lat1, "Lng":lng1, "url":url1, "ID":ids1 })
df1.head()

,Restaurant,Type,Price,Rating,Address,Lat,Lng,url,ID
0,Cafe Vienna,Austrian,££,5,235 Brompton road,51.496826,-0.168447,https://www.yelp.com/biz/cafe-vienna-london?ad...,-_6mjiQuPMMR7VvLb3v92A
1,Fischer's,Austrian,£££,4,50 Marylebone High Street,51.521616,-0.151700,https://www.yelp.com/biz/fischers-london?adjus...,apqNvjbaB20wozywrLNPiQ
2,Kipferl,Coffee & Tea,££,4,20 Camden Passage,51.535248,-0.103393,https://www.yelp.com/biz/kipferl-london-6?adju...,xqpUr61KFa1Xx721-E6l_A
3,The Delaunay,Modern European,£££,4,55 Aldwych,51.513112,-0.118255,https://www.yelp.com/biz/the-delaunay-london-3...,QTRkMjYHXAVROidXkkt7Ow
4,Zeitgeist,German,££,4,49 - 51 Black Prince Road,51.491333,-0.118202,https://www.yelp.com/biz/zeitgeist-london-3?ad...,sen5D3KKE0penBC7d5GlUQ

In [6]:
#2nd set of 50 records 51-100 
lndr_params2 = {"term":"Austrian","location":"London","limit":50,"offset":51}
lndr_response2 = requests.get(search_api_url, headers=headers, params=lndr_params2)
lndr2 = lndr_response2.json()
display(lndr2)
#print(lndr_response2.url)
#print(lndr_response2.status_code)

{'businesses': [],
 'total': 15,
 'region': {'center': {'longitude': -0.135955810546875,
   'latitude': 51.51283552118349}}}

In [7]:
#Create a for loop to capture the data of the second set of 50 records 51-100

#Create Empty Lists
lat2=[]
lng2=[]
address2=[]
name2=[]
title2=[]
price2=[]
rating2=[]
ids2=[]
url2=[]

#Set Counter to 0
i = 0

#For Loop with Try/Except Error
for i in (lndr2["businesses"]):
    try:
        lat2.append (i["coordinates"]["latitude"])
        lng2.append (i["coordinates"]["longitude"])
        address2.append (i["location"]["address1"])
        name2.append (i["name"])    
        title2.append(i["categories"][0]["title"])
        price2.append (i["price"])
        rating2.append (i["rating"])
        ids2.append (i["id"])
        url2.append (i["url"])
    except(KeyError,IndexError):
        print("Skipping, Not Found")
        price2.append("")
        rating2.append("")
        ids2.append("")
        url2.append("")

In [8]:
#Create DataFrame of the next 50 records collected 51-100
df2 = pd.DataFrame({"Restaurant": name2,"Type": title2, "Price":price2, "Rating":rating2, "Address":address2, "Lat":lat2, "Lng":lng2, "url":url2, "ID":ids2 })
df2.head()

Empty DataFrame
Columns: [Restaurant, Type, Price, Rating, Address, Lat, Lng, url, ID]
Index: []

In [9]:
#3rd set of 50 records 101-150
lndr_params3 = {"term":"Austrian","location":"London","limit":50,"offset":101}
lndr_response3 = requests.get(search_api_url, headers=headers, params=lndr_params3)
lndr3 = lndr_response3.json()
display(lndr3)
#print(lndr_response3.url)
#print(lndr_response3.status_code)

{'businesses': [],
 'total': 15,
 'region': {'center': {'longitude': -0.135955810546875,
   'latitude': 51.51283552118349}}}

In [10]:
#Create a for loop to capture the data of the third iteration of 50 records 101-150

#Create Empty Lists
lat3=[]
lng3=[]
address3=[]
name3=[]
title3=[]
price3=[]
rating3=[]
ids3=[]
url3=[]

#Set Counter to 0
i = 0

#For Loop with Try/Except Error
for i in (lndr3["businesses"]):
    try:
        lat3.append (i["coordinates"]["latitude"])
        lng3.append (i["coordinates"]["longitude"])
        address3.append (i["location"]["address1"])
        name3.append (i["name"])    
        title3.append(i["categories"][0]["title"])
        price3.append (i["price"])
        rating3.append (i["rating"])
        ids3.append (i["id"])
        url3.append (i["url"])
    except(KeyError,IndexError):
        print("Skipping, Not Found")
        price3.append("")
        rating3.append("")
        ids3.append("")
        url3.append("")

In [11]:
#Create DataFrame of the third set of 50 records collected 101-150 
df3 = pd.DataFrame({"Restaurant": name3,"Type": title3, "Price":price3, "Rating":rating3, "Address":address3, "Lat":lat3, "Lng":lng3, "url":url3, "ID":ids3 })
df3.head()

Empty DataFrame
Columns: [Restaurant, Type, Price, Rating, Address, Lat, Lng, url, ID]
Index: []

In [12]:
#4th set of 50 records 151-200
lndr_params4 = {"term":"Austrian","location":"London","limit":50,"offset":151}
lndr_response4 = requests.get(search_api_url, headers=headers, params=lndr_params4)
lndr4 = lndr_response4.json()
display(lndr4)
#print(lndr_response4.url)
#print(lndr_response4.status_code)

{'businesses': [],
 'total': 15,
 'region': {'center': {'longitude': -0.135955810546875,
   'latitude': 51.51283552118349}}}

In [13]:
#Create a for loop to capture the data of the fourth set of 50 records 151-200

#Create Empty Lists
lat4=[]
lng4=[]
address4=[]
name4=[]
title4=[]
price4=[]
rating4=[]
ids4=[]
url4=[]

#Set Counter to 0
i = 0

#For Loop with Try/Except Error
for i in (lndr4["businesses"]):
    try:
        lat4.append (i["coordinates"]["latitude"])
        lng4.append (i["coordinates"]["longitude"])
        address4.append (i["location"]["address1"])
        name4.append (i["name"])    
        title4.append(i["categories"][0]["title"])
        price4.append (i["price"])
        rating4.append (i["rating"])
        ids4.append (i["id"])
        url4.append (i["url"])
    except(KeyError,IndexError):
        print("Skipping, Not Found")
        price4.append("")
        rating4.append("")
        ids4.append("")
        url4.append("")

In [14]:
#Create DataFrame of the last 50 records collected 151-200
df4 = pd.DataFrame({"Restaurant": name4,"Type": title4, "Price":price4, "Rating":rating4, "Address":address4, "Lat":lat4, "Lng":lng4, "url":url4, "ID":ids4 })
df4.head()

Empty DataFrame
Columns: [Restaurant, Type, Price, Rating, Address, Lat, Lng, url, ID]
Index: []

In [15]:
london_restaurants_df = pd.concat([df1,df2,df3,df4], sort=True)
london_restaurants_df.shape

(15, 9)

In [16]:
column_order = ["Restaurant","Type","Rating","Price","Address","Lat","Lng","url","ID"]
london_restaurants_df = london_restaurants_df[column_order]
london_restaurants_df = london_restaurants_df.sort_values(["Type"], ascending=True)
london_restaurants_df = london_restaurants_df.reset_index(drop=True)
london_restaurants_df

,Restaurant,Type,Rating,Price,Address,Lat,Lng,url,ID
0,Cafe Vienna,Austrian,5,££,235 Brompton road,51.496826,-0.168447,https://www.yelp.com/biz/cafe-vienna-london?ad...,-_6mjiQuPMMR7VvLb3v92A
1,Fischer's,Austrian,4,£££,50 Marylebone High Street,51.521616,-0.151700,https://www.yelp.com/biz/fischers-london?adjus...,apqNvjbaB20wozywrLNPiQ
2,The Delaunay Counter,Cafes,,,55 Aldwych,51.513112,-0.118255,,
3,Kipferl,Coffee & Tea,4,££,20 Camden Passage,51.535248,-0.103393,https://www.yelp.com/biz/kipferl-london-6?adju...,xqpUr61KFa1Xx721-E6l_A
4,Kalendar Cafe,Coffee & Tea,3.5,££,15a Swains Lane,51.562003,-0.149828,https://www.yelp.com/biz/kalendar-cafe-london?...,HmZmhDt7fFG39K7hGo3mqA
5,Marcus,French,4,££££,The Berkeley,51.501661,-0.155697,https://www.yelp.com/biz/marcus-london-2?adjus...,ov2m0xEjirn1Gll0MOhUqw
6,Zeitgeist,German,4,££,49 - 51 Black Prince Road,51.491333,-0.118202,https://www.yelp.com/biz/zeitgeist-london-3?ad...,sen5D3KKE0penBC7d5GlUQ
7,German Gymnasium,German,4,£££,1 Kings Boulevard,51.532398,-0.125420,https://www.yelp.com/biz/german-gymnasium-lond...,4IpNjfnu3VnM8p7_i4or4Q
8,Katzenjammers,German,3.5,££,24 Southwark Street,51.504827,-0.091032,https://www.yelp.com/biz/katzenjammers-london?...,jcBeMcH_nAaDDJotomqs-g
9,Munich Cricket Club,German,3.5,££,1 Abbey Orchard Street,51.498072,-0.132526,https://www.yelp.com/biz/munich-cricket-club-l...,GXGXX8Eapy5yBpLTx-N1kw
10,Oblix At The Shard,Lounges,4,££££,Level 32 The Shard,51.505253,-0.086987,https://www.yelp.com/biz/oblix-at-the-shard-lo...,DJH9kKABJZHkJ4Xz8b168w
11,The Delaunay,Modern European,4,£££,55 Aldwych,51.513112,-0.118255,https://www.yelp.com/biz/the-delaunay-london-3...,QTRkMjYHXAVROidXkkt7Ow
12,10 Greek Street,Modern European,4.5,£££,10 Greek Street,51.514498,-0.131063,https://www.yelp.com/biz/10-greek-street-londo...,PEgAoJeVtVAbmuNKUWa-wg
13,Stein's,Pubs,3.5,££,Richmond Towpath,51.455546,-0.304016,https://www.yelp.com/biz/steins-london?adjust_...,eXNSn0FwCeSmDHDlDWzv5w
14,The Paperworks,Street Vendors,,,48 - 50 Newington Causeway,51.498024,-0.098499,,

In [17]:
# Save the dataframe to a csv file
london_restaurants_df.to_csv('Resources/London_Restaurants_Austrian.csv')